name: AMD Daily Check

on:
  schedule:
    # 18:00 UTC = 20:00 Heure de Paris
    - cron: '0 18 * * *'
  workflow_dispatch: # CE BOUTON PERMET DE TESTER EN CLIQUANT

jobs:
  check-amd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Tracker
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py
